theme: minima
minima:
  skin: dark
title: Digital Health
description: EMRs by Joumana Salahaldin

plugins:
  - jekyll-titles-from-headings

titles_from_headings:
  enabled:     true
  strip_title: false
  collections: false
